# Generated by Django 6.0 on 2025-12-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_number', models.CharField(max_length=100)),
                ('shopware_verified', models.BooleanField(default=False)),
                ('quivers_verified', models.BooleanField(default=False)),
                ('middelware_verified', models.BooleanField(default=False)),
                ('order_create_date', models.DateTimeField()),
                ('payment_details', models.CharField(default='Unknown', max_length=15)),
                ('additional_details', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_number'], name='orders_orde_order_n_60e070_idx'), models.Index(fields=['created_at'], name='orders_orde_created_95a77a_idx')],
            },
        ),
    ]
